# Generated by Django 5.0 on 2024-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_remove_orders_amount_remove_orders_oid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name2',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='oid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
