# Generated by Django 5.0 on 2024-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_remove_orders_name2_orders_amount_orders_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=500000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amountpaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.BooleanField(default=False),
        ),
    ]
